### ISSUE TITLE
Addition of All Contributors Photos in Readme | Readme Updation

### ISSUE THREAD

**Issue by Shariq2003** [MadhavKrishanGoswami/InkCode-Fusion#11]
We can add all the contributor's photos in Readme file as a token of appreciation for their work.

Please assign this to me.

![image](https://github.com/user-attachments/assets/24846984-f3d2-44a4-8d2b-2a5025d1ceb9)
Like this

**Comment by MadhavKrishanGoswami** [comment]
Hey @Shariq2003 ! Just wanted to let you know that this issue is already being addressed in #9 . Feel free to check it out for updates!

Thanks for your understanding! 🌟

**Comment by Shariq2003** [comment]
But @MadhavKrishanGoswami i think the assignee is not working on this, as its already 3 days passed away.

**Comment by MadhavKrishanGoswami** [comment]
I’ll assign you to this issue so you can take a look at it. 😊
Please ping me there so I can assign you!

Let me know if you need any help!

**Comment by Shariq2003** [comment]
Okay sir, I have ping you there please look into that then I will raise a PR in just 15-20 mint max

**Comment by Shariq2003** [comment]
If you believe then assign this to me and open this issue sir
