### ISSUE TITLE
Implement Code Execution on Worker Server

### ISSUE THREAD

**Issue by MadhavKrishanGoswami** [MadhavKrishanGoswami/InkCode-Fusion#13]
Currently, the main server sends code to the worker server for execution. However, the worker server is returning a dummy output: 
```json
{ "output": "Dummy Output from worker" }
```
We need to modify the worker server so that it can actually execute Python code and return the real output.

**Problem or Use Case**:
The current setup is a placeholder that doesn't execute any code. This feature is required to handle real Python code execution. It will enable the worker server to process actual code submitted by users and return the correct results or error messages from the Python interpreter.

**Proposed Solution**:
- Modify the worker server to execute Python code securely.
- Ensure the worker can handle standard input, output, and errors for Python code.
- Capture and return both successful output and error messages as part of the response to the main server.
- Handle execution limits, like timeouts and memory usage, to avoid long-running or resource-heavy tasks.

**Alternatives Considered**:
- Initially focus on Python execution, with future plans to support other languages.
- Another option could be integrating a third-party service for Python execution, but building it natively gives more control over the execution environment.

**Additional Context**:
This feature will greatly enhance the worker server’s functionality by allowing real-time Python code execution, moving us toward a functional coding platform.

**Comment by ifeelsam** [comment]
i think i get it, can i try? 
will ask if further info needed

**Comment by MadhavKrishanGoswami** [comment]
Absolutely, go ahead! Feel free to try it out, and don't hesitate to reach out if you need more details or run into any issues. Good luck! 😊

**Comment by ifeelsam** [comment]
just got working on it....
got the basic print statement working.. but i need to look more into syntax parsing
you can see in the video 
im still looking into it

https://github.com/user-attachments/assets/b90b0623-3a90-4664-b465-55cf8682e8b7

**Comment by ifeelsam** [comment]
check out 


resolve #19

**Comment by ifeelsam** [comment]
added a pr #19  
lmk if something's wrong

**Comment by MadhavKrishanGoswami** [comment]
Hey @ifeelsam! Thank you for raising the PR. I'll review it and get back to you as soon as possible.

**Comment by NK-Works** [comment]
@MadhavKrishanGoswami I can work on this issue 
please assign me
can make the pr by midnight

**Comment by Saachi26** [comment]
Hey!
Thank you for offering to help, but this issue has already been resolved and closed. 
 Feel free to explore other open issues.
