### ISSUE TITLE
Meeting title does not sync across users

### ISSUE THREAD

**Issue by Saachi26** [MadhavKrishanGoswami/InkCode-Fusion#16]
The meeting title is editable by participants, and while the title changes on the screen of the user who edits it, the change is not reflected for other members of the meeting. This causes a synchronization issue where the meeting title is inconsistent across different users.

**Proposed Solution**

- Emit the updated meeting title to the server when a user edits it.
- Ensure that the server broadcasts the new title to all participants in the room.
- Add a listener on the front-end to receive and update the title when it's changed by any participant.

**Comment by PriyanshuPz** [comment]
Hi @MadhavKrishanGoswami,
May I work on this issue

**Comment by Saachi26** [comment]
Absolutely, go ahead! Feel free to ask if you have any questions.

**Comment by PriyanshuPz** [comment]
@Saachi26 Is `readme` is old as I am facing problem in setting up this??

**Comment by MadhavKrishanGoswami** [comment]
Hello @priyanshuverma-dev,
Could you please share a screenshot of the error you're encountering so I can assist you better?

**Comment by PriyanshuPz** [comment]
`yarn` just worked when I commented.
All good here @MadhavKrishanGoswami.
How are you BRO!
OH! Good EVENING

**Comment by MadhavKrishanGoswami** [comment]
Glad to hear it's working! 😄
I'm doing great, thanks for asking!
Good evening to you too!
