### ISSUE TITLE
Create a CONTRIBUTING.md file

### ISSUE THREAD

**Issue by Saachi26** [MadhavKrishanGoswami/InkCode-Fusion#17]
Create a CONTRIBUTING.md file. This file will serve as a guide for potential contributors, outlining the steps and guidelines for contributing effectively to the project.

Proposed Structure for CONTRIBUTING.md

- Setting up the project: Instructions on forking the repository, cloning, and creating a new branch.
- Code of Conduct: Reference to a code of conduct for maintaining a respectful community.
- Issues: Guidelines for reporting bugs and requesting features.
- Pull Requests: Instructions on how to submit a pull request, including guidelines for descriptions and linking issues.
- Commit Messages: Standards for writing clear commit messages.
- Coding Guidelines: Information about the tech stack and coding style to follow.
- Development Workflow: Steps for running the development environment, testing, and building the project.
- License: Information regarding the project's license.

**Comment by ifeelsam** [comment]
can i?

**Comment by MadhavKrishanGoswami** [comment]
Absolutely go ahead!

**Comment by ifeelsam** [comment]
i added necessary stuff, didn't feel like adding too much stuff to overwhelm the contributors, happy to add it if that's what you want you can see the the pr #25

**Comment by AnujSaha0111** [comment]
I want to work on it. Can you please assign it to me?

**Comment by MadhavKrishanGoswami** [comment]
@AnujSaha0111 Absolutely, I'd love to have you contribute! Let's just wait for @ifeelsam to confirm if they're working on it. If not, you can go ahead and pick it up!

**Comment by MadhavKrishanGoswami** [comment]
Hello! @AnujSaha0111 you can start working on this!

**Comment by AnujSaha0111** [comment]
> Hello! @AnujSaha0111 you can start working on this!

Solved it #33

**Comment by Dipanita45** [comment]
I want to work on this issue
