### ISSUE TITLE
Improve User Experience By Enhancing UI

### ISSUE THREAD

**Issue by iamsohelx** [MadhavKrishanGoswami/InkCode-Fusion#27]
Hey @MadhavKrishanGoswami in your website The /Start Page ui is not looking good, We could make it better by Changing the ui and adding smooth animation and transition.
![StartPage](https://github.com/user-attachments/assets/cfc11e60-05d7-48a7-9e2a-c0dc80125de2)

**Comment by iamsohelx** [comment]
Hey @MadhavKrishanGoswami i can help you to improve the ui, could you please assign this task to me.

**Comment by MadhavKrishanGoswami** [comment]
Absolutely go ahead!
Let me know if you need any help!

**Comment by iamsohelx** [comment]
> Absolutely go ahead! Let me know if you need any help!

Thank you ☺️, could you please add labes to it and level (level1, level2, level3)

**Comment by iamsohelx** [comment]
Hiii @MadhavKrishanGoswami  it is okay or should i add or change something?
 
## Features Added

- Changed the ui
- Added Fonts
- Copy button is only visible when you generate room code

![TimeGiven](https://github.com/user-attachments/assets/5ddf5b73-3589-406f-992d-6a7a48425e05)

**Comment by MadhavKrishanGoswami** [comment]
The fonts look great, but could we maintain the bubbly and pastel theme instead of going with a more boxy design? It would really help keep the playful and light aesthetic. Thanks!

**Comment by iamsohelx** [comment]
> The fonts look great, but could we maintain the bubbly and pastel theme instead of going with a more boxy design? It would really help keep the playful and light aesthetic. Thanks!

Okay sure brother let me change it

**Comment by iamsohelx** [comment]
@MadhavKrishanGoswami hey brother I just wanted to ask that, should I change the colour of button or keep it as it is

**Comment by MadhavKrishanGoswami** [comment]
I think you can keep the colors or just accent them a bit if you would like

**Comment by iamsohelx** [comment]
@MadhavKrishanGoswami Now Brother?
![Happy](https://github.com/user-attachments/assets/a8d8342c-97d3-4d16-bb13-0b43da870f2e)

**Comment by MadhavKrishanGoswami** [comment]
Nice it looks great 👍

**Comment by iamsohelx** [comment]
> Nice it looks great 👍
@MadhavKrishanGoswami 

Thank you 😊
Can I make a pull request?

**Comment by MadhavKrishanGoswami** [comment]
Absolutely you can raise a pull request I'll review it and I'll merge it! Thanks for the great work

**Comment by iamsohelx** [comment]
> Absolutely you can raise a pull request I'll review it and I'll merge it! Thanks for the great work

@MadhavKrishanGoswami Thank you brother 😊. I have made the pull request you can review it.
