### ISSUE TITLE
Missing LICENSE.md

### ISSUE THREAD

**Issue by LitZeus** [MadhavKrishanGoswami/InkCode-Fusion#35]
LICENSE.md plays an important part in the understanding of the project usage. Introducing one to the repository will make the documentation stronger and richer!

I would like to do the task under the `gssoc-ext` label

**Comment by MadhavKrishanGoswami** [comment]
Hello @LitZeus,

Thanks for raising the issue regarding the missing LICENSE.md. Just to let you know, this is already being worked on, so no need to worry about it!

However, if you'd like, feel free to pick up other open issues or create a new one. Your contributions are always appreciated!

Cheers

**Comment by LitZeus** [comment]
Sure! @MadhavKrishanGoswami
