### ISSUE TITLE
Code Execution

### ISSUE THREAD

**Issue by haseebzaki-07** [MadhavKrishanGoswami/InkCode-Fusion#44]
The code in the editor is not running. I want the code to execute and show the output in the output section.

**Comment by Saachi26** [comment]
Hello @haseebzaki-07,

Thank you for your enthusiasm and eagerness to contribute! 😊 I wanted to let you know that this task is already being discussed in issue  #13 . Feel free to check it out and join the conversation there.

Excited to see your ideas and contributions!
