### ISSUE TITLE
Dockerize the project by creating Dockerfile for Project Containerization and Deployment.

### ISSUE THREAD

**Issue by Suraj-kumar00** [MadhavKrishanGoswami/InkCode-Fusion#46]
### Description:
It is frustrating to setup the local development environment for everyone so...

We need to containerize our project for easier deployment and consistency across various environments. The Dockerfile should include the necessary configurations to build and run our application in a Docker container.

I would like to work on this issue as I'm proficient in `Cloud/DevOps` practices. I can:
1. Dockerize the project:
2. Dockerize the project with `minimal docker image`.
3. Can Create a workflow to `build` and `push` the docker images to the `DockerHub Account` but for this I will need the credentials of your dockerhub account to push to docker image on your account.(_**If you want me to implement this feature we can discuss about how to add the credentials to your this repo**_)

> **This will simplify the running of the application on the local machine and make easier for to developers to work efficiently.** 

`Labels`: This issue will lie between
- [x] Level 2 or Level3
- [X] Enhancement
- [X] Hacktoberfest
- [X] gssoc

Please assign this issue to me so that I can work on it.

**Comment by MadhavKrishanGoswami** [comment]
Hi @Suraj-kumar00,

Thank you for the suggestion! Just to let you know, the application is already containerized with Docker. If you have any other ideas or improvements, feel free to contribute!

Thanks again for your input!

**Comment by Suraj-kumar00** [comment]
Oh It's my bad I haven't saw the project correctly. Actually it's dockerized.

**Comment by MadhavKrishanGoswami** [comment]
No worries!
