### ISSUE TITLE
LICENSE FILE MISSING 

### ISSUE THREAD

**Issue by ABHISIKTAcommits** [MadhavKrishanGoswami/InkCode-Fusion#50]
I WANT TO ADD MIT LICENSE FILE AND LINK THE SAME IN THE README.
ON CLICKING THE LINK OF LICENSE ITS SHOWING 404 ERROR !
![Screenshot 2024-10-19 123348](https://github.com/user-attachments/assets/d138fdca-7d5c-4a9e-ab17-969de121adfd)

- PLEASE ASSIGN THE ISSUE TO ME AND MARK THE LABELS OF gssoc-ext hacktoberfest-accepted and level.

![Screenshot 2024-10-17 151725](https://github.com/user-attachments/assets/6ed6072a-cfc8-402b-87c5-5cd6e45ec116)

**Comment by Saachi26** [comment]
Thank you for pointing out the issue! 
We appreciate your offer to help but will manage this internally. We really appreciate your willingness to help, and we’d love for you to keep contributing to new issues or improvements in the future. Thanks for your understanding!
