### ISSUE TITLE
Add File Storage Documentation to README

### ISSUE THREAD

**Issue by banasmita24** [MadhavKrishanGoswami/InkCode-Fusion#57]
## Description:
Hi, I went through your repo. I want to enhance the README to include a section that details the structure and purpose of files and folders within the project. This documentation will help new contributors and maintainers understand where to find specific files.

## Requirements:

- List key folders and files with a brief description of each.
- Include any subdirectory structures if relevant, and explain the organization.
- README includes a "File Structure" or "Project Structure" section

Please assign me this under hactoberfest-accepted, gssoc-ext and respective level.

Thank you :)

**Comment by MadhavKrishanGoswami** [comment]
Hi @banasmita24 ,

Thanks for the suggestion! Since the project is in active development and the structure is still evolving, we’ll hold off on adding a "File Structure" section for now. Feel free to open another issue or contribute to an existing one!
