### ISSUE TITLE
🚀 Automate Connections with GitHub Actions!

### ISSUE THREAD

**Issue by amiya-cyber** [MadhavKrishanGoswami/InkCode-Fusion#58]
We can implement github workflows for the following things:

Auto comment on issue Closed and Opened
Auto comment on PR mergs
Auto comment on PR raises
Using this workflows makes you'r repo more interactive !

please assign me and i'm expecting a level3 with gssoc-ext and hacktoberfest-accepted label
@MadhavKrishanGoswami

**Comment by MadhavKrishanGoswami** [comment]
Hi @amiya-cyber ,

Thanks for the suggestion! This issue is already being handled internally as part of ongoing development. Feel free to explore other issues or open a new one with any enhancement ideas!

Cheers! 😊
