### ISSUE TITLE
📝[DOCS] adding Stargazers and Forkers section to readme.md

### ISSUE THREAD

**Issue by amiya-cyber** [MadhavKrishanGoswami/InkCode-Fusion#60]
Issue Description
adding Stargazers and Forkers section to readme.md

Stargazers

Use Case:

1. Bookmarking Projects
2. Discovering Popularity

Benefits:

1. Visibility
2. Feedback Indicator
3. Community Engagement

Forkers

Use Case:

1. Creating Personal Copies
2. Contributing Back

Benefits:

1. Encouraging Innovation
2. Easy Collaboration
3. Building Ownership

![2024-10-29 (1)](https://github.com/user-attachments/assets/92b03317-27e7-4efb-a975-6a3a49df2c0b)

please assign and add level2 label @MadhavKrishanGoswami

**Comment by MadhavKrishanGoswami** [comment]
Thank you for opening this issue! While we appreciate your input, we don’t find this enhancement necessary at the moment. Additionally, it’s generally not ideal to demand specific actions like assigning levels for issues, as we understand the appropriate complexity level for each one. If you're looking to contribute, feel free to check out other open issues. Your input is appreciated!
cheers
