### ISSUE TITLE
ADD HACKTOBERFEST AND GSSOC BANNER ON THE README

### ISSUE THREAD

**Issue by amiya-cyber** [MadhavKrishanGoswami/InkCode-Fusion#61]
Describe the bug

The README file is missing the Hacktoberfest and GSSoC banners. The issue is to add these banners at the appropriate location to showcase the project's involvement in these events.

To Reproduce

1. Go to the GitHub repository.
2. Navigate to the README.md file.
3. Scroll down to check for banners related to Hacktoberfest and GSSoC.
4. See that the banners are missing.

Expected behavior

The Hacktoberfest and GSSoC banners should appear on the README file, ideally at the top, to indicate that the project is part of these events.

Additional context

The banners can be sourced from the official Hacktoberfest and GSSoC websites. They should align with the current styling of the README file, and possibly, they could be centered for better visibility.

![2024-10-29](https://github.com/user-attachments/assets/bc776c67-ae3c-443e-9463-79346b542620)

ADD LABELS HACKTOBERFEST AND GSSOC EXT 24 AND LEVEL 2 OR LEVEL 3
ASSIGN ME THE WORK
THANK YOU @MadhavKrishanGoswami  !

**Comment by MadhavKrishanGoswami** [comment]
Hey @amiya-cyber Thank you for opening this issue! While we appreciate your input, we don’t find this enhancement necessary at the moment. Additionally, it’s generally not ideal to demand specific actions like assigning levels for issues, as we understand the appropriate complexity level for each one. If you're looking to contribute, feel free to check out other open issues. Your input is appreciated!
