### ISSUE TITLE
Adding a program section 

### ISSUE THREAD

**Issue by Aman-G-upta** [MadhavKrishanGoswami/InkCode-Fusion#63]
![Screenshot 2024-10-29 083757](https://github.com/user-attachments/assets/99d87252-9c31-4a15-89c0-d68e92b18d40)
Please assign me under this issue @MadhavKrishanGoswami

**Comment by MadhavKrishanGoswami** [comment]
Sure, Go for it!

**Comment by AnushkaChouhan25** [comment]
Hii @MadhavKrishanGoswami Can you assign me this issue, I want to contribute to it, and I will complete it within one day.
