### ISSUE TITLE
Adding Social Media Links to the Footer of README

### ISSUE THREAD

**Issue by amiya-cyber** [MadhavKrishanGoswami/InkCode-Fusion#66]
This READ ME lacks a contact us section.
We can Add a visually appealing footer to the README that includes links to key social media profiles, making it easy for users to connect and stay updated. The footer should align with the project's branding, feature accessible icons (e.g., GitHub, Twitter, LinkedIn), and be mobile-friendly. Each link must be verified to open correctly, ideally in a new tab where possible. This enhancement will improve user engagement and provide quick access to our social platforms.

please assign and add level2 

![2024-11-01 (6)](https://github.com/user-attachments/assets/44a6cfbb-d068-4aae-977f-47d278088300)

**Comment by MadhavKrishanGoswami** [comment]
Hi @amiya-cyber ,


Thank you for opening this issue! While we appreciate your input, we don’t find this enhancement necessary at the moment. Additionally, it’s generally not ideal to demand specific actions like assigning levels for issues, as we understand the appropriate complexity level for each one. If you're looking to contribute, feel free to check out other open issues. Your input is appreciated!
cheers
