### ISSUE TITLE
Add Stargazers and Frokers to Readme.md ✨

### ISSUE THREAD

**Issue by AnushkaChouhan25** [MadhavKrishanGoswami/InkCode-Fusion#68]
![image](https://github.com/user-attachments/assets/75c9520e-2b7f-42f3-b6b0-ebfd776a7f31)

**Comment by MadhavKrishanGoswami** [comment]
Thank you for opening this issue! While we appreciate your input, we don’t find this enhancement necessary at the moment. 

If you're looking to contribute, feel free to check out other open issues. Your input is appreciated!
cheers
