### ISSUE TITLE
Want to add security policy 

### ISSUE THREAD

**Issue by Dipanita45** [MadhavKrishanGoswami/InkCode-Fusion#69]
Want to add security policy to protect the website against the harms 

Please assign me the issue

**Comment by MadhavKrishanGoswami** [comment]
Could you please provide me with additional information on this?

**Comment by Dipanita45** [comment]
I will add security file in.md extension

**Comment by Dipanita45** [comment]
Please assign me the issue

**Comment by MadhavKrishanGoswami** [comment]
Thank you for pointing out the issue!
We appreciate your offer to help but will manage this internally. We really appreciate your willingness to help, and we’d love for you to keep contributing to new issues or improvements in the future. Thanks for your understanding!
